### ISSUE TITLE
Error HTTP 400 when trying to get a token

### ISSUE THREAD

**Issue by quentin-decre** [fregante/chrome-webstore-upload#55]
I can't retreive a token, it fails with an response HTTP 400.
Your lib seems great, but I am stuck with this. Any idea ?

Here is the code

```javascript
const store = chromeWebstoreUpload({
  extensionId: 'fggnebfeaknhlgjoedpghkcgbcbplebg',
  clientId: 'SECRET',
  refreshToken: 'SECRET',
})
console.log('Store is defined', store)
async function deploy(publish = false) {
  try {
    // const token = await store.fetchToken()
    // console.log('Token fetched', token)
    const myZipFile = fs.createReadStream('./build/jarvis-extension.zip')
    const uploadResult = await store.uploadExisting(myZipFile)
    console.log('Extension has been uploaded', uploadResult)
  } catch (err) {
    console.error(err)
  }
}
```

And here is the nodeJS logs :

```
Store is defined APIClient {
  extensionId: 'fggnebfeaknhlgjoedpghkcgbcbplebg',
  clientId: 'SECRET',
  refreshToken: 'SECRET'
}
HTTP 4967: call onSocket 0 0
HTTP 4967: createConnection www.googleapis.com:443:::::::::::::::::: {
  protocol: 'https:',
  hostname: 'www.googleapis.com',
  hash: '',
  search: '',
  pathname: '/oauth2/v4/token',
  path: null,
  href: 'https://www.googleapis.com/oauth2/v4/token',
  method: 'POST',
  retry: {
    limit: 2,
    methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
    statusCodes: [
      408, 413, 429, 500,
      502, 503, 504, 521,
      522, 524
    ],
    errorCodes: [
      'ETIMEDOUT',
      'ECONNRESET',
      'EADDRINUSE',
      'ECONNREFUSED',
      'EPIPE',
      'ENOTFOUND',
      'ENETUNREACH',
      'EAI_AGAIN'
    ],
    maxRetryAfter: Infinity,
    calculateDelay: [Function: calculateDelay]
  },
  headers: {
    'user-agent': 'got (https://github.com/sindresorhus/got)',
    'content-type': 'application/json',
    accept: 'application/json',
    'content-length': '198',
    'accept-encoding': 'gzip, deflate, br'
  },
  hooks: {
    init: [],
    beforeRequest: [],
    beforeRedirect: [],
    beforeRetry: [],
    beforeError: [],
    afterResponse: []
  },
  cache: undefined,
  dnsCache: undefined,
  decompress: true,
  throwHttpErrors: true,
  followRedirect: true,
  isStream: false,
  responseType: 'text',
  resolveBodyOnly: false,
  maxRedirects: 10,
  prefixUrl: '',
  methodRewriting: true,
  ignoreInvalidCookies: false,
  http2: false,
  allowGetBody: false,
  https: undefined,
  pagination: {
    transform: [Function: transform],
    paginate: [Function: paginate],
    filter: [Function: filter],
    shouldContinue: [Function: shouldContinue],
    countLimit: Infinity,
    backoff: 0,
    requestLimit: 10000,
    stackAllItems: true
  },
  parseJson: [Function: parseJson],
  stringifyJson: [Function: stringifyJson],
  cacheOptions: {},
  url: URL {
    href: 'https://www.googleapis.com/oauth2/v4/token',
    origin: 'https://www.googleapis.com',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'www.googleapis.com',
    hostname: 'www.googleapis.com',
    port: '',
    pathname: '/oauth2/v4/token',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  username: '',
  password: '',
  shared: undefined,
  cacheHeuristic: undefined,
  immutableMinTimeToLive: undefined,
  ignoreCargoCult: undefined,
  _defaultAgent: Agent {
    _events: [Object: null prototype] {
      free: [Function],
      newListener: [Function: maybeEnableKeylog]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    defaultPort: 443,
    protocol: 'https:',
    options: { path: null },
    requests: {},
    sockets: { 'www.googleapis.com:443::::::::::::::::::': [] },
    freeSockets: {},
    keepAliveMsecs: 1000,
    keepAlive: false,
    maxSockets: Infinity,
    maxFreeSockets: 256,
    maxTotalSockets: Infinity,
    totalSocketCount: 0,
    scheduling: 'fifo',
    maxCachedSessions: 100,
    _sessionCache: { map: {}, list: [] },
    [Symbol(kCapture)]: false
  },
  port: 443,
  host: 'www.googleapis.com',
  servername: 'www.googleapis.com',
  _agentKey: 'www.googleapis.com:443::::::::::::::::::',
  [Symbol(isNormalizedAlready)]: true,
  [Symbol(request)]: [Function: request]
}
HTTP 4967: sockets www.googleapis.com:443:::::::::::::::::: 1 1
HTTP 4967: write ret = true
(node:4967) Warning: Setting the NODE_DEBUG environment variable to 'http' can expose sensitive data (such as passwords, tokens and authentication headers) in the resulting log.
HTTP 4967: outgoing message end.
HTTP 4967: AGENT incoming response!
HTTP 4967: AGENT socket.destroySoon()
HTTP 4967: CLIENT socket onClose
HTTP 4967: removeSocket www.googleapis.com:443:::::::::::::::::: writable: false
HTTP 4967: HTTP socket close
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/home/qdecre/jarvis/apps/extension/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1638827791539,
    socket: 1638827791548,
    lookup: 1638827791559,
    connect: 1638827791572,
    secureConnect: 1638827791602,
    upload: 1638827791603,
    response: 1638827791643,
    end: 1638827791665,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 9,
      dns: 11,
      tcp: 13,
      tls: 30,
      request: 1,
      firstByte: 40,
      download: 22,
      total: 126
    }
  }
}

**Comment by fregante** [comment]
The keys you entered are likely to be invalid. Make sure that there aren’t any extra spaces anywhere. https://github.com/fregante/chrome-webstore-upload/search?q=bad+request+is%3Aissue&type=Issues
