### ISSUE TITLE
Error: Option "extensionId" is required

### ISSUE THREAD

**Issue by Blaumaus** [fregante/chrome-webstore-upload#56]
The broken workflow is located here: https://github.com/Swetrix/swetrix-browser/runs/4769383847?check_suite_focus=true

For some reason, the chrome extension is not uploaded and throws the new error:
```
npm WARN exec The following package was not found and will be installed: chrome-webstore-upload-cli@2
- Fetching token
Error
Error: Option "extensionId" is required
    at new APIClient (/home/runner/.npm/_npx/f7427b1617d822ea/node_modules/chrome-webstore-upload/index.js:20:23)
    at module.exports (/home/runner/.npm/_npx/f7427b1617d822ea/node_modules/chrome-webstore-upload/index.js:78:12)
    at fetchToken (file:///home/runner/.npm/_npx/f7427b1617d822ea/node_modules/chrome-webstore-upload-cli/wrapper.js:34:20)
    at doAutoPublish (file:///home/runner/.npm/_npx/f7427b1617d822ea/node_modules/chrome-webstore-upload-cli/cli.js:72:25)
    at init (file:///home/runner/.npm/_npx/f7427b1617d822ea/node_modules/chrome-webstore-upload-cli/cli.js:171:15)
    at file:///home/runner/.npm/_npx/f7427b1617d822ea/node_modules/chrome-webstore-upload-cli/cli.js:179:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
```

The `CLIENT_ID`, `REFRESH_TOKEN` and `EXTENSION_ID` are set as the workflow Environment secrets.

**Comment by fregante** [comment]
Ensure that they're actually set in the secrets because it looks like only the Firefox keys are present:


![image](https://user-images.githubusercontent.com/1402241/148865319-76ec7e33-0774-4ced-9449-25829f64d9fc.jpeg)

**Comment by Blaumaus** [comment]
My bad.
The Chrome-related secrets were set as environment values while it required them to be set as repository secrets.
Thank you for your help and for your opensource contributions!
