### ISSUE TITLE
TypeError: RequestInit: duplex option is required when sending a body.

### ISSUE THREAD

**Issue by alexandredepape** [fregante/chrome-webstore-upload#78]
```bash
Run npx chrome-webstore-upload-cli@3 upload --source chrome-extension-cfd726002d89d231ebfd214435baf76305827fca.zip --auto-publish
npm WARN exec The following package was not found and will be installed: chrome-webstore-upload-cli@3.1.0
- Fetching token
- Uploading chrome-extension-cfd726002d8[9](https://github.com/alexandredepape/yazyk/actions/runs/7360389303/job/20036472601#step:4:10)d231ebfd214435baf76305827fca.zip
TypeError: RequestInit: duplex option is required when sending a body.
    at Object.fetch (node:internal/deps/undici/undici:[11](https://github.com/alexandredepape/yazyk/actions/runs/7360389303/job/20036472601#step:4:12)730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async APIClient.uploadExisting (file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload/index.js:34:25)
    at async doAutoPublish (file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload-cli/cli.js:74:28)
    at async init (file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload-cli/cli.js:[16](https://github.com/alexandredepape/yazyk/actions/runs/7360389303/job/20036472601#step:4:17)7:9)
    at async file:///home/runner/.npm/_npx/da388c0a4eab99e8/node_modules/chrome-webstore-upload-cli/cli.js:[17](https://github.com/alexandredepape/yazyk/actions/runs/7360389303/job/20036472601#step:4:18)6:5
Error: Process completed with exit code 1.
```
Ever since https://github.com/fregante/chrome-webstore-upload-cli/pull/74

Any idea ?

**Comment by fregante** [comment]
- https://github.com/nodejs/node/issues/46221

I'll fix it soon

**Comment by fregante** [comment]
This has been fixed: https://github.com/fregante/chrome-webstore-upload/releases/tag/v3.0.1

Can you test again?

**Comment by alexandredepape** [comment]
Thanks, will test
